// generated by "sampctl package generate"

#include "tid_account.inc"
#include "tid_login.inc"
#include "tid_menu.inc"
#include "tid_mysql.inc"
#include "tid_signup.inc"
#include "ui_intro.inc"
#include "tempo-id.inc"

main() 
{
	// write tests for libraries here and run "sampctl package run"
}
